#!/usr/bin/env bash

#PBS -N toy-mpi-acc
#PBS -j oe
#PBS -A NMMM0013
#PBS -l select=1:ncpus=2:mpiprocs=2
#PBS -l walltime=00:10:00
#PBS -q develop

module purge 2> /dev/null
module load ncarenv/24.12
module load nvhpc cuda cray-mpich ncarcompilers
# module load linaro-forge/24.1 # if needed for debug
ml

# mpibind --ddt-connect -- ./mpi-acc_toy.out # For linaro-forge 
mpibind --line-buffer -- ./mpi-acc_toy.out
